hash-format = "sha256"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "2d3cbf3d77196a08a014270238740515c1b634bc11ad83a51140d7bcfc62d6b3"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "1fc1e482945dff68e6aab34b22d61d054a6177869408ed4af3fef6117a33faab"
metafile = true

[[files]]
file = "mods/armor-hud.pw.toml"
hash = "2fd994edb8b89dc3712869770cc8a207bb97bf8cb4eb4f7c09d71f2e1c010c82"
metafile = true

[[files]]
file = "mods/axiom.pw.toml"
hash = "5d803700375154c02bfa9e7d3f64b634708568f4d22cd3671cddcd9b3c7d2ab5"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "fa1d1286d8bc03ae99442535edd1e3c134ea859b861089e21d8b503e7cba4c67"
metafile = true

[[files]]
file = "mods/blur-plus.pw.toml"
hash = "12c4cfdac7981abd1c17758c78f8cd3d115610e2c07b017b2e4a61a975aaaa76"
metafile = true

[[files]]
file = "mods/boat-item-view.pw.toml"
hash = "6d717e11f5a11194004d8879b5c1e46448394855211ce8ac1937ae40895f2c27"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
hash = "6088be62ff0bc4e93388ba995418a376a1b7dfd062cce84bc36349b34ffa4af6"
metafile = true

[[files]]
file = "mods/carpet-tis-addition.pw.toml"
hash = "bf2fe1ad823f0f3b50605274e759dd308116a3d1d3ea9a64291d2ce1b90001da"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "b6986c7bdec6840b8a344b4028b0a52be10460f2630223ca88db681b36cd5efa"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "0e073702f4562edac6258fd01f8b921628adf48fdd7e70209d93f4978753a0ce"
metafile = true

[[files]]
file = "mods/clientsort.pw.toml"
hash = "94f43cd957f4c6bbf49b21e0d8eb923ed91fefe0bc2a18a0c75175bf79de5c66"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "717d8ac591dba59be4767a179e1359747561e54ccfcac42161fd6bf54339a78b"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "b152c75412428e5f53667cb0836fa1323ca93cbd925e456239710a2e261d9963"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "a90139b002d632ba9256cb3e7e877945bf8e3afa5b191d1adc83c5e3eb72da4c"
metafile = true

[[files]]
file = "mods/dark-loading-screen.pw.toml"
hash = "716b671d0b15ea17c788c571620eac83207bb2b6e8dbe0d33319838478f21efc"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "b6dd8c2e3c0b386b2551844c81c41940554f373c24aa8a35f20dfd63022e59fb"
metafile = true

[[files]]
file = "mods/essential.pw.toml"
hash = "9abc4f23709fc0e9e7f4a4ae259a4616c23f14695f660eda5bdb1c6873427786"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "cbda4f1881cfb9f054395a3db225df4202d1f2e7bd0ed27d803b837fcf728621"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "0df5b608f6521692c1434583a92f944e303881dbad0fcd98a5b5d37d7c22367a"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "186a261ded1911abf559dce21b22eadc1e96de7767982e58f458b82a89a924ba"
metafile = true

[[files]]
file = "mods/flashback.pw.toml"
hash = "e56ab572b86cd0f11f62baa45556a21cf767197a6f028d967814166b10ed3784"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "d74f72f3bf13c4ef7d60b6e2defecd3c7af77ed9be7764cf1ed10ea1fd707a1f"
metafile = true

[[files]]
file = "mods/freecam.pw.toml"
hash = "9d12f51a932b25751b7595ca46439a30bee2c26bf6d9913ccc9a27ade1972f36"
metafile = true

[[files]]
file = "mods/gamma-utils.pw.toml"
hash = "cc4a12cee04af27f3ca40ebe8d9509292a35f7b944cb5892de9adfaeecae6fda"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "deb841bd032e5b2722df01d2743b1fc67be20540b9608ee29501909f37ba3015"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "4ed061d122cb39f34ed730984c7bcf03437250f24a21975203bb4598d7d86a14"
metafile = true

[[files]]
file = "mods/item-scroller.pw.toml"
hash = "3ceeca043fd967760acb5698a1611fa50cd4c1a2bc6419d777a9dc53f30da480"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "8f6e0157b42ba668c0ba9aa7eff94b3b91a8f58bcd357e574d70a7b160d4337c"
metafile = true

[[files]]
file = "mods/lighty.pw.toml"
hash = "eebcb6dd93f1d09f39bf699c11f213cab1d0f8f3c248cbe8b79659633759a051"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "47e38eeda17a991d3201448e71f68081893c8e7aee15b44088dc86eacfc8ca43"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "84957275e9dc6f07f4244ce3303536e3d73b0e72eb1696ccd024168a52c29c98"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "df5ce30f6ac464f7b06400e03568d2b9087dd1849fd8c21a2381fe2f666338b6"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "ae2060c6233ba1715c06f687148af5b2fbd9ac511c28d653fe2887ad7ecb1fc1"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "b261880bd245c83c51b729199452da12b0766a4aa0210fc79d0c48161cbfcc49"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "5dd45d5fd5e1ae2bd521b93a70b83c69b57ada18f424c6562d8c6ea9980cfb3e"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "204a4b3b041fad4bb4dc543c74d540fcf239710494d2130cebe700bf1d8a7805"
metafile = true

[[files]]
file = "mods/moremousetweaks.pw.toml"
hash = "ae32e710270b91145d2f18b5cd0fb38af3a2614fae98aa1bf1ff101ec243554c"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "dc24a4cc0ad484d6593997c197ea602fac4d98c45dab0de6421e704c3851acd9"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "70d7b2bca719eca2b3a1447228b868abdc633c38121652d49f4e34380c44339d"
metafile = true

[[files]]
file = "mods/noisiumforked.pw.toml"
hash = "a3b275726e1953dd46c5ef4637d2ab82500c9b58be1c25325a704a9423c5deba"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "ba9cdad1c81aa5fbae79686c0eac7daaaca67990f0dd4a6f4ece5def1d17a924"
metafile = true

[[files]]
file = "mods/open-parties-and-claims.pw.toml"
hash = "d788235233cd7bb10444760f354161d730ce1c504976cfdf91bd26fcd05c9e26"
metafile = true

[[files]]
file = "mods/packet-fixer.pw.toml"
hash = "84cb0dcad9ac46d22adba4fb7924951affa6ac5e46027a3b25fa9a0db8d91b2b"
metafile = true

[[files]]
file = "mods/ping-wheel.pw.toml"
hash = "ab077e767cf4974b5225967f690be78e994b8cc6c7ce6411060f303e7173fd19"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "e674752dd4dd07c33d9b94f6e19c15ef893c356c3c5ed77aeaf35cf6d2325130"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "ad2c2880cd91b5d927f3bfdba657189997cdd6dd30f46ee0d969a68de2bb2ad8"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "6cc155f0633b2187f5bc71357ab1d82c1d49f9592bcbd73191ec1001c98c342b"
metafile = true

[[files]]
file = "mods/simple-music-control.pw.toml"
hash = "bcd4938c174cb691ce4b356857b79a3d94dfbd9cbb4a33c764fee273a0048ccf"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "8c80e3393ce1fb38159f02af4dd3a7aba0b656945aac8c3da5aef04b22915e35"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "bb7064282571976ed2bbe266bcf5e525d6d661aeea89649e4d604327973cf92d"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "279ea1bb4b776be9176fe34416e2132e37abfce4483def54177091cc0f2faade"
metafile = true

[[files]]
file = "mods/tweakermore.pw.toml"
hash = "715b86d4669a9f6b7416bbc6545bc4abd1d2ddda401be261b29fb7a1199f9f2d"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "c5092ec9a074c3afcc2312c985d0829e023dcfa3524597ec1c4902359d5c78dc"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "dba564c761870715c46e527e182ece9d0c50ae96c8c4e3af3f2b567e2816565d"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "993390d4661a77aa83c8416f75addfccaf7cee0a7a7311a21742b2036700b5ac"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "53c8bc02c9b10610c43fc29127039036217e33a95ab2ea2d6ac291987266ef89"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "e71ac6769675de1d2338a13e116f2aefcc8965ab0bc18b75a53572531c1447dd"
metafile = true
