name = "Cave Game"
author = "TheMicCraft"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58035589007b738bcda305cb52535fc2d4611f29e7325275c756d7a6396e098d"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.9"]
