name = "Cave Game"
author = "TheMicCraft"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df00677580bd49ec4374b1284449f6c82cfc9b521ab7e57623c656766bc54734"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.9"]
