name = "Cave Game"
author = "TheMicCraft"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c4ec02302e9085f8da11f078699cb0c65ddec7a891892fe7890be13d2c8e3cf"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.9"]
